services:
  backend:
    build: .
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      POSTGRES_URI: postgresql+psycopg://admin:pass@localhost:5432/ims
      REDIS_URL: redis://redis:6379/0
      ENV: production
    restart: always

  db:
<<<<<<< HEAD
    image: postgres:15
=======
    image: postgres:18
>>>>>>> b76be9586e6f8524df22e83853fe08b120d4011e
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: ims
    ports:
      - "5432:5432"
    volumes:
<<<<<<< HEAD
      - postgresdata:/var/lib/postgresql/data
=======
      - postgresdata:/var/lib/postgresql
>>>>>>> b76be9586e6f8524df22e83853fe08b120d4011e

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data/redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  postgresdata:
  redisdata:
