[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ims-backend"
version = "0.1.0"
description = "IMS backend and database integration"
requires-python = ">=3.11"
dependencies = [
  "python-dotenv>=1.1",
  "fastapi>=0.118.3",
  "pymongo>=4.15.3",
]

[project.optional-dependencies]
test = ["pytest>=8.4", "flake8>=7.3","psycopg2-binary>=2.9"]

[tool.setuptools.packages.find]
where = ["backend"]
include = ["*"]

