name: Backend-Integration-Testing

on:
  push:
    branches: [ "main" ]

jobs:
  backend-ci:
    name: Build & Test (Backend)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.10'

      # Build images quietly, then run tests only
      - name: installing Dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel \
          && pip install flake8 pytest || true

      - name: Run Flake8
        run: |
          flake8 backend --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 backend --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics
          pytest test
