name: Base Trigger
on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  backend:
    uses: ./.github/workflows/backend-action.yml
    with:
      pr_repo: ${{ github.repository }}
      pr_ref: ${{ github.ref_name }}

  frontend:
    uses: ./.github/workflows/frontend-action.yml
    with:
      pr_repo: ${{ github.repository }}
      pr_ref: ${{ github.ref_name }}
